skwasjer/IbanNet

- Changelog.md
- src/IbanNet/Builders/BankAccountBuilderException.cs
- src/IbanNet/Builders/BbanBuilder.cs
- src/IbanNet/Builders/BuilderExtensions.cs
- src/IbanNet/Builders/IBankAccountBuilder.cs
- src/IbanNet/Builders/IbanBuilder.cs
- src/IbanNet/Extensions/ArrayExtensions.cs
- src/IbanNet/Resources.Designer.cs
- src/IbanNet/Resources.resx
- test/IbanNet.Tests/Builders/BankAccountBuilderTests.cs
- test/IbanNet.Tests/Builders/BuilderExtensionsTests.cs
- test/IbanNet.Tests/Extensions/ArrayExtensionsTests.cs
Adds two simple builders for IBAN and BBAN.
- both builders depend on a country code supported by the registry
- ability to auto pad account numbers
- computes valid check digit (IBAN only)
Note that both builders do not ensure actual validity, as you can supply the methods any textual data.
In relation to #21 as a prerequisite to support generating pseudo random account numbers (for testing purposes).
> Add builders for BBAN and IBAN.

- appveyor.yml
- src/IbanNet.DependencyInjection.Autofac/IbanNetModule.cs
- src/IbanNet.DependencyInjection.ServiceProvider/ServiceCollectionExtensions.cs
- src/IbanNet/Builders/BuilderExtensions.cs
- src/IbanNet/Registry/IIbanGenerator.cs
- src/IbanNet/Registry/IbanGenerator.cs
- src/IbanNet/Resources.Designer.cs
- src/IbanNet/Resources.resx
- test/IbanNet.DependencyInjection.Autofac.Tests/Specs/ShouldResolveGeneratorSpec.cs
- test/IbanNet.DependencyInjection.ServiceProvider.Tests/Specs/ShouldResolveGeneratorSpec.cs
- test/IbanNet.Tests/Registry/IbanGeneratorTests.cs
- test/TestHelpers/Specs/ShouldResolveGeneratorSpec.cs
See #21 
Use case: (integration) testing with generated IBAN's
- Adds a new class `IbanGenerator` which can be used to generate random IBAN's for testing purposes. Each `Generate()` invocation returns a new random IBAN.
- Only accepts country codes that are registered in the provided registry (via ctor, default is all 'known' IbanNet countries).
- Generates valid IBAN check digits.
- Generates IBAN's that pass validation (guaranteed, but not considering custom rules).
- Registered in dependency injection containers as interface `IIbanGenerator`.
```csharp
var generator = new IbanGenerator();
var randomIban = generator.Generate("NL");
```
```csharp
var generator = services.GetRequiredService<IIbanGenerator>();
var randomIban = generator.Generate("GB");
```
Note: does NOT support specifying …
> feat: Adds an IBAN generator based on patterns functionality

- Changelog.md
- src/IbanNet.FluentValidation/FluentIbanValidator.cs
- src/IbanNet.FluentValidation/IbanNet.FluentValidation.csproj
- src/IbanNet.FluentValidation/RuleBuilderExtensions.cs
- test/IbanNet.FluentValidation.Tests/FluentIbanValidatorTests.cs
- test/IbanNet.FluentValidation.Tests/IbanNet.FluentValidation.Tests.csproj
- test/IbanNet.FluentValidation.Tests/IntegrationTests.cs
- test/IbanNet.FluentValidation.Tests/RuleBuilderExtensionsTests.cs
Closes #30 
Breaking change:
- Updates FluentValidation dependencies to v10.x
- `PropertyValidator` is deprecated
> (+semver:breaking) Refactor to FluentValidation v10

- .github/workflows/codeql-analysis.yml
See https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> chore: upgrade CodeQL to v2

- src/IbanNet.CodeGen/Swift/Patches/FranceBranchPatch.cs
- src/IbanNet.CodeGen/Swift/Patches/RecordPatcher.cs
- src/IbanNet.CodeGen/Swift/SwiftCsvRecord.cs
- src/IbanNet/Registry/Swift/SwiftRegistryProvider.cs
- src/IbanNet/Registry/Swift/SwiftRegistryProvider.tt
- test/IbanNet.Tests/Issues/77_FranceIsMissingBranch.cs
Addresses #77 at the code generation level. 
Adds an abstract way of adding specific patches before actually generating the registry provider. New (future) patches can easily be added by implementing `RecordPatcher`, which will then be applied automatically when regenerating the provider.
This way we do not have to expose internal types or change the immutable aspect of the registry (even though this can and should still be considered as a separate change).
> fix: adds branch information to FR

- src/IbanNet.DataAnnotations/IbanAttribute.cs
- src/IbanNet.DataAnnotations/IbanNet.DataAnnotations.csproj
- src/IbanNet.FluentValidation/FluentIbanValidator.cs
- src/IbanNet.FluentValidation/IbanNet.FluentValidation.csproj
- src/IbanNet.FluentValidation/RuleBuilderExtensions.cs
- src/IbanNet/Iban.cs
- src/IbanNet/IbanParser.cs
- src/IbanNet/IbanValidator.cs
- src/IbanNet/Internal/InputNormalization.cs
- test/IbanNet.DataAnnotations.Tests/AspNetIntegrationTest.cs
- test/IbanNet.DataAnnotations.Tests/AspNetWebHostFixture.cs
- test/IbanNet.DataAnnotations.Tests/IbanAttributeTests.cs
- test/IbanNet.DataAnnotations.Tests/IbanNet.DataAnnotations.Tests.csproj
- test/IbanNet.DataAnnotations.Tests/InputModel.cs
- test/IbanNet.DataAnnotations.Tests/IntegrationTests.cs
- test/IbanNet.DataAnnotations.Tests/StrictInputModel.cs
- test/IbanNet.DataAnnotations.Tests/TestController.cs
- test/IbanNet.FluentValidation.Tests/IntegrationTests.cs
- test/IbanNet.Tests/IbanParserTests.cs
- test/IbanNet.Tests/IbanTests.cs
- test/IbanNet.Tests/IbanValidatorIntegrationTests.cs
- test/IbanNet.Tests/Internal/InputNormalizationTests.cs
Move normalization to parser, such that validator is always validating strict. 
Add `Strict`-property (default true) to `IbanAttribute` and `FluentIbanValidator<T>` and its associated `Iban` rule extension. When Strict=true, the input must strictly match the IBAN format rules. When Strict=false, whitespace is ignored and strict character casing enforcement is disabled (meaning, the user can input in lower and uppercase). 
This mode is a bit more forgiving when dealing with user-input. However it does require after successful validation, that you parse the user input with `IIbanParser` to normalize/sanitize the input and to be able to format the IBAN in correct electronic format.
Strict defaults to true.
See #93
Examples:
```csharp
// DataAnnotations
public class InputModel
{
[Iban(Strict …
```
> feat(validator): move normalization to parser, such that validator is always validating strictly

- src/IbanNet.DataAnnotations/IbanNet.DataAnnotations.csproj
- src/IbanNet.DataAnnotations/Resources.nl.resx
- src/IbanNet.FluentValidation/IbanNet.FluentValidation.csproj
- src/IbanNet.FluentValidation/Resources.nl.resx
- src/IbanNet/IbanNet.csproj
- src/IbanNet/Resources.nl.resx
This adds Dutch ("NL") translations for all existing .resx files in all various projects.
Fixes #94
I was debating how (and if) to include updated test coverage for these changes. All current tests keep passing on my machine. But adding test coverage in a maintainable way presents a few choices about the test setup.
First up, I have confirmed to some degree with tests that this is working, by modifying an existing test into this one:
```csharp
[Fact]
public void When_creating_instance_it_should_have_expected_message___AdhocTestOfLocalization()
{
// Adhoc fact to verify if localization of error messages is working.
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("nl-NL");
var country = new IbanCountry("NL") { DisplayName = "The display name" };
var sut = new …
```
> Add "nl" resx files

- .github/workflows/codeql-analysis.yml
- .github/workflows/dotnetcore.yml
- .github/workflows/sonarcloud.yml
- Directory.Build.props
- Update to v3 actions
- Remove .NET Core 2.1 SDK install
- `dotnet test` also .NET 4.x (works now since Mono has been included in runner images)
- Suppress .NET EOL warnings
> Refactor/update CI to build with latest

- src/IbanNet/Iban.cs
- test/IbanNet.Tests/IbanTests.cs
See #133
Implements `IParseable<T>` with a dependency on the default registry. The `IbanParser` must still be used when customization of the registry is desired (eg. registering other provider(s)) until the considerations mentioned in #133 are addressed.
> feat: implement IParsable<T> on Iban type

- test/Directory.Build.targets
- test/IbanNet.Tests/IbanNet.Tests.csproj
_Created as PR as it might be easier to discuss after prof of concept implementation. (Ok I admit, I was eager to get started and began a PR before reading project guidelines)_
Set common dependabot updated packages in test projects to wildcard (to reduce dependabot noise)
Internal only used PackageReferences in test projects, such as Microsoft.NET.Test.Sdk, Microsoft.TestPlatform.ObjectModel, FluentAssertions and also Newtonsoft.Json in Test project do not affect resulting package, so having these packages being non immutable should not pose any issues.
There is possible issues with builds/tests not being immutable, but they should be theoretical at best. Reduced maintenance and noise from dependabot should be worth it.
_Happy to update/fix for "Conventional Commits" but might need some …
> chore(deps): Set test projects PackageReferences to wildcard version

- test/Directory.Build.targets
- test/IbanNet.DataAnnotations.Tests/IbanAttributeTests.cs
- test/IbanNet.DependencyInjection.Autofac.Tests/Specs/ShouldResolveCustomService.cs
- test/IbanNet.DependencyInjection.ServiceProvider.Tests/Specs/ShouldResolveCustomService.cs
- test/IbanNet.FluentValidation.Tests/FluentIbanValidatorTests.cs
- test/IbanNet.FluentValidation.Tests/RuleBuilderExtensionsTests.cs
- test/IbanNet.Tests/Builders/BuilderExtensionsTests.cs
- test/IbanNet.Tests/DependencyInjection/DependencyResolverAdapterTests.cs
- test/IbanNet.Tests/DependencyInjection/FluentAssertions/IbanNetOptionsBuilderStubAssertions.cs
- test/IbanNet.Tests/DependencyInjection/FluentAssertions/IbanNetOptionsBuilderStubExtensions.cs
- test/IbanNet.Tests/DependencyInjection/IbanNetOptionsBuilderTests.cs
- test/IbanNet.Tests/IbanParserTests.cs
- test/IbanNet.Tests/IbanTests.cs
- test/IbanNet.Tests/IbanValidatorTests.cs
- test/IbanNet.Tests/Json/IbanJsonConverterTests.cs
- test/IbanNet.Tests/Registry/IbanRegistryTests.cs
- test/IbanNet.Tests/Registry/Patterns/PatternTests.cs
- test/IbanNet.Tests/TypeConverters/IbanTypeConverterTests.cs
- test/IbanNet.Tests/Validation/DefaultValidationRuleResolverTests.cs
- test/IbanNet.Tests/Validation/Rules/Mod97RuleTests.cs
- test/TestHelpers/IbanValidatorStub.cs
- test/TestHelpers/Specs/ConfiguredMultipleRulesSpec.cs
- test/TestHelpers/Specs/ShouldPreserveStaticValidatorSpec.cs
- test/TestHelpers/Specs/ShouldResolveCustomService.cs
- test/TestHelpers/Specs/ShouldSetStaticValidatorSpec.cs
- test/TestHelpers/TestValues.cs
Due to addition of SponsorLink to Moq, I've decided to switch to NSubstitute. The GDPR/trust breach is concerning, but while this has since been resolved, it seems the author of Moq will continue to impose SponsorLink to anyone using his libraries and expose them to nag messages, longer build times, etc. I would love sponsorships too, but I do not agree with this method of getting financial compensation.
See https://github.com/moq/moq/issues/1372
> chore(deps): replace Moq with NSubstitute

- examples/AspNetCore/AspNetCoreExample.csproj
- examples/AspNetCore/Controllers/MvcController.cs
- examples/AspNetCore/Controllers/WebApiController.cs
- examples/AspNetCore/Models/InputModel.cs
- examples/AspNetCore/Pages/Error.cshtml.cs
- examples/AspNetCore/Pages/Index.cshtml.cs
- examples/AspNetCore/Pages/RazorPage.cshtml.cs
- examples/AspNetCore/Pages/WebApi.cshtml.cs
- examples/AspNetCore/Pages/_Layout.cshtml
- examples/AspNetCore/Pages/_ViewImports.cshtml
- examples/AspNetCore/Program.cs
- examples/AspNetCore/Startup.cs
- examples/AspNetCore/Views/Mvc/Index.cshtml
- examples/AspNetCore/Views/Shared/_Layout.cshtml
- examples/AspNetCore/Views/Shared/_ViewImports.cshtml
- examples/AutoMapper/AutoMapperExample.csproj
- examples/AutoMapper/Domain/Payment.cs
- examples/AutoMapper/Mappings/PaymentProfile.cs
- examples/AutoMapper/Program.cs
- examples/GenerateIbans/GenerateIbans.csproj
- examples/LimitCountries/LimitCountries.csproj
- Bump IbanNet dependencies in examples.
- Adjust AspNetCore example to use non-strict validation as it works better with the UI presentation.
- Update AutoMapper example to work with latest version of AutoMapper.
Closes #158 (addressing the second task, option 4)
> docs: update IbanNet dependency in examples [skip ci]

- .github/workflows/codeql-analysis.yml
- .github/workflows/dotnetcore.yml
- .github/workflows/sonarcloud.yml
There is an issue with latest SDK (7.0.400) on Linux with .NET Framework causing builds with .NET Framework to fail. 
https://github.com/microsoft/vstest/issues/4549
Unfortunatey, it becomes preinstalled with latest [GitHub runner images](https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md), so have to remove it for now.
> Opting to lower version (eg. 7.0.307) via installer is not sufficient!
> ci: remove latest .NET SDK temporarily

- .github/workflows/sonarcloud.yml
This change ensures we run SonarCloud analysis in context of PR, while having access to repo secrets. However, we must protect from outside PR's 'stealing' our secrets. This problem is solved by requiring external contribs/PR's to be manually approved before this workflow can run, by adding a minimum of 1 reviewer to environment protection rules on env 'external'.
This mechanism is described in this blog:
https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets
> Require approval on PR

- .github/workflows/sonarcloud.yml
PR decoration was broken due to a previous change (6065d99) where we now check out detached PR head. Because of this, I assume SonarQube is unable to determine branch and target and thus not decorating the PR.
Fix by explicitly providing PR nr and branches
> ci(sonar): PR decoration was broken

- .github/workflows/sonarcloud.yml
Fixes warning "The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token."
> ci(sonar): fix warning "The property 'sonar.login' is deprecated"

- .github/workflows/sonarcloud.yml
Fixes warning:
> The version of Java (11.0.20) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17. Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)
> ci(deps): bump NodeJS/Java versions to fix deprecation warning of SonarScanner

- Directory.Build.props
- src/IbanNet.DataAnnotations/IbanNet.DataAnnotations.csproj
- src/IbanNet.FluentValidation/IbanNet.FluentValidation.csproj
- src/IbanNet/IbanNet.csproj
chore: reduce build runtime by excluding satellite assemblies (in tests)
style: move DE satellite RESX under the parent RESX (this does not affect `dotnet pack` of our runtime assemblies)
> chore: reduce build runtime by excluding satellite assemblies (in tests)

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/sonarcloud.yml
- Directory.Build.props
- src/Directory.Build.targets
- src/IbanNet.DataAnnotations/IbanNet.DataAnnotations.csproj
- src/IbanNet.DependencyInjection.Autofac/IbanNet.DependencyInjection.Autofac.csproj
- src/IbanNet.DependencyInjection.ServiceProvider/IbanNet.DependencyInjection.ServiceProvider.csproj
- src/IbanNet.FluentValidation/IbanNet.FluentValidation.csproj
- src/IbanNet/IbanNet.csproj
- src/IbanNet/Registry/IbanRegistry.cs
- test/IbanNet.Benchmark/BenchmarkResults.md
- test/IbanNet.Benchmark/IbanNet.Benchmark.csproj
- test/IbanNet.Benchmark/ValidatorBenchmark.cs
- test/IbanNet.CodeGen.Tests/IbanNet.CodeGen.Tests.csproj
- test/IbanNet.DataAnnotations.Tests/IbanNet.DataAnnotations.Tests.csproj
- test/IbanNet.DependencyInjection.Autofac.Tests/IbanNet.DependencyInjection.Autofac.Tests.csproj
- test/IbanNet.DependencyInjection.ServiceProvider.Tests/IbanNet.DependencyInjection.ServiceProvider.Tests.csproj
- test/IbanNet.FluentValidation.Tests/IbanNet.FluentValidation.Tests.csproj
- test/IbanNet.Tests/IbanNet.Tests.csproj
- test/TestHelpers/TestHelpers.csproj
- Adds .NET 8 target framework
- Uses new `FrozenDictionary<,>` in `IbanRegistry`
- Retested for performance regressions/improvements
> The AppVeyor build will break as it is missing .NET 8 preview.
> feat(net8): add .NET 8 target framework

- test/IbanNet.Tests/IbanParserTests.cs
- test/IbanNet.Tests/IbanTests.cs
- test/IbanNet.Tests/IbanValidatorIntegrationTests.cs
- test/IbanNet.Tests/Internal/InputNormalizationTests.cs
- test/IbanNet.Tests/Registry/IbanCountryTests.cs
Fixes xUnit1012: Null should not be used for type parameter 'nnn' of type 'string'. Use a non-null value, or convert the parameter to a nullable type.
> fix(xUnit1012): address static code analysis

- src/IbanNet/Properties/AssemblyInfoAttributes.cs
- src/IbanNet/Registry/Patterns/Pattern.cs
- src/IbanNet/Registry/Swift/SwiftPattern.cs
- src/IbanNet/Registry/Swift/SwiftRegistryProvider.cs
- src/IbanNet/Registry/Swift/SwiftRegistryProvider.tt
- test/IbanNet.Benchmark/BenchmarkResults.md
During validation of an IBAN, of all the `IIbanValidationRule`s most time is spent in the `IsMatchingStructureRule` validator. To increase performance, we can make use of code generation to generate a custom `SwiftPattern` class per country in the `SwiftRegistryProvider`, in which the actual pattern validation is unrolled. This provides a significant performance increase as we no longer have to flow through the general purpose pattern validator, avoiding all the loops and branching. 
Performance gains varies per .NET runtime and per country pattern, but goes as high as ~75% and at least ~25%. 
Note:
- Loop unrolling throws (on generation) for non-fixed length patterns. This is not an issue atm. because no IBAN defined in SWIFT registry is currently of variable length, even though the spec …
> perf: use code generation to unroll pattern match per country (SWIFT only)

- src/IbanNet/Extensions/SwissIbanExtensions.cs
- src/IbanNet/Resources.Designer.cs
- src/IbanNet/Resources.resx
- src/IbanNet/Validation/Results/InvalidQrIbanResult.cs
- src/IbanNet/Validation/Rules/QrIbanRule.cs
- test/IbanNet.Tests/Validation/Rules/IsValidQrIbanRuleTests.cs
QR IBAN validation is added as a standalone rule. This rule is only valid for QR IBAN's and hence not part of the default ruleset.
> QR IBAN validation is added as a standalone rule.

- src/Directory.Build.targets
- src/IbanNet.DataAnnotations/IbanNet.DataAnnotations.csproj
- src/IbanNet/Builders/BankAccountBuilderException.cs
- src/IbanNet/CheckDigits/Calculators/InvalidTokenException.cs
- src/IbanNet/IbanFormatException.cs
- src/IbanNet/IbanNet.csproj
- src/IbanNet/Registry/IbanCountryCodeComparer.cs
- src/IbanNet/Registry/Patterns/PatternException.cs
- src/IbanNet/Registry/Patterns/PatternToken.cs
- src/IbanNet/Resources.Designer.cs
- src/IbanNet/Resources.ca.resx
- src/IbanNet/Resources.de.resx
- src/IbanNet/Resources.nl.resx
- src/IbanNet/Resources.resx
- test/Directory.Build.targets
- test/IbanNet.Benchmark/IbanNet.Benchmark.csproj
- test/IbanNet.DataAnnotations.Tests/IbanNet.DataAnnotations.Tests.csproj
- test/IbanNet.DependencyInjection.Autofac.Tests/IbanNet.DependencyInjection.Autofac.Tests.csproj
- test/IbanNet.DependencyInjection.ServiceProvider.Tests/IbanNet.DependencyInjection.ServiceProvider.Tests.csproj
- test/IbanNet.DependencyInjection.ServiceProvider.Tests/Specs/ShouldValidateOptionsRegistrySpec.cs
- test/IbanNet.FluentValidation.Tests/IbanNet.FluentValidation.Tests.csproj
- test/IbanNet.Tests/Builders/BankAccountBuilderExceptionTests.cs
- test/IbanNet.Tests/CheckDigits/Calculators/InvalidTokenExceptionTests.cs
- test/IbanNet.Tests/IbanFormatExceptionTests.cs
- test/IbanNet.Tests/IbanNet.Tests.csproj
- test/IbanNet.Tests/Registry/Patterns/PatternExceptionTests.cs
- test/IbanNet.Tests/Registry/Patterns/PatternTokenTests.cs
After a long time, but for maintainability sake, I have decided to drop .NET Standard 1.6 as a target framework for the packages:
- IbanNet 
- IbanNet.DataAnnotations
.NET Standard 2.x remains available to reference IbanNet in .NET (Framework) projects.
> chore: drop .NET Standard 1.6 support

- .github/workflows/main.yml
- .github/workflows/sonarcloud.yml
Disables xunit's AppDomain logic. Hopefully this resolves the random CI failures.
> ci: attempt to fix random AppDomain unloads in CI on macos/mono

- src/IbanNet.CodeGen/IbanNet.CodeGen.csproj
- src/IbanNet.CodeGen/Swift/SwiftCsvRecord.cs
- src/IbanNet/Properties/AssemblyInfoAttributes.cs
- src/IbanNet/Registry/Swift/SwiftPattern.cs
- src/IbanNet/Registry/Swift/SwiftRegistryProvider.tt
Make `SwiftPattern` fully internal, instead of public in `DEBUG`. This way, the API surface of IbanNet is consistent in DEBUG/RELEASE.
Instead, expose the parsed pattern via the import record/DTO and allow CodeGen to have access to IbanNet internals.
> chore: make SwiftPattern fully internal, instead of public in DEBUG.

- test/Directory.Build.targets
The change in #206 was not active because that is a new option since 2.5.1.
> chore(deps): bump xunit.runner.visualstudio to 2.8.2.

- src/IbanNet.CodeGen/IbanNet.CodeGen.csproj
- src/IbanNet.CodeGen/Wikipedia/Loader.cs
- src/IbanNet.CodeGen/Wikipedia/ParseResult.cs
- src/IbanNet.CodeGen/Wikipedia/WikiRecord.cs
- src/IbanNet.CodeGen/Wikipedia/WikiResponse.cs
- src/IbanNet.CodeGen/Wikipedia/WikiResult.cs
- src/IbanNet/Registry/Wikipedia/WikipediaRegistryProvider.cs
- src/IbanNet/Registry/Wikipedia/WikipediaRegistryProvider.tt
- test/IbanNet.Tests/Registry/Wikipedia/WikipediaRegistryProviderTests.cs
Updated `WikipediaRegistryProvider` which adds a good number of countries (all of which are also already in `SwiftRegistryProvider` with more metadata). Moved some of the logic into `CodeGen` library, and also sorted by country code.
> feat: updated WikipediaRegistryProvider

- src/IbanNet.CodeGen/Wikipedia/Loader.cs
- src/IbanNet.CodeGen/Wikipedia/ParseResult.cs
- src/IbanNet.CodeGen/Wikipedia/WikiResponse.cs
Just some cleanup/STA fixes in de CodeGen library, not affecting any release packages
> fix: STA warnings

- src/IbanNet/IbanFormatException.cs
This satisfies CA2235 code warning. `ValidationResult` was never intended to be serializable.
> fix(CA2235): mark IbanFormatException.Result (backing field) as non-serializable

- .github/workflows/sonarcloud.yml
Java is already being setup via an action, so this is unnecessary overhead. JRE provisioning was added somewhere last year.
> Note: this change only becomes effective after merge, since the sonarcloud workflow runs actions from `main` branch as a security measure.
Log output before change:
```
Preparing working directories...
13:05:44.882  Updating build integration targets...
13:05:46.687  Using SonarCloud.
13:05:47.094  The JRE provisioning is a time consuming operation.
JRE provisioned: OpenJDK17U-jre_x64_linux_hotspot_17.0.11_9.tar.gz.
If you already have a compatible java version installed, please add either the parameter "/d:sonar.scanner.skipJreProvisioning=true" or "/d:sonar.scanner.javaExePath=<PATH>".
```
> ci(sonar): disable JRE provisioning

- test/IbanNet.Benchmark/BenchmarkResults.md
- test/IbanNet.Benchmark/ValidatorPerProvider.cs
Only compares for a single specific country, so it is only an indication but gives a rough idea of the speed/alloc deltas.
> perf: add benchmark that provides comparison between providers
